### ISSUE TITLE
Where to get libsoda?

### ISSUE THREAD

**Issue by sk-** [biemster/gasr#1]
@biemster Could you add a paragraph hinting at where one could get the compiled library and the data to run it. I looked everywhere in the repo, but it seems they haven't yet put any of the sources there, even though it's supposed to be on `/third_party`.

**Comment by biemster** [comment]
I doubt that SODA will ever be open sourced, as the speech team at google wants to keep there work close to the chest, as can be read [on their review system](https://chromium-review.googlesource.com/c/chromium/src/+/2404156/13#message-b825c77cec893a7f66b23b5f4d3f37375bf361f1):
```
The Speech team was concerned about unauthorized repurposing of their components,
so we initially implemented the client that called the SODA binary in an internal repo to
obfuscate the interface between Chrome and SODA.
```
The library is distributed as an extension, as you can see in [soda_component_installer.cc](https://github.com/chromium/chromium/blob/master/chrome/browser/component_updater/soda_component_installer.cc).
So you need to download this the same way as the chrome process would (or wait for Chrome 90, and find it on your hard drive somewhere).
On top of that, the functionality is [secured with an API key](https://github.com/chromium/chromium/commit/90a2ac585e61be98d3dd3dd47f5566110df63700) and stack verification, so when you get your hands on the blob, you'll need to get around that as well.

I intentionally did not provide any info on how to obtain libsoda, mainly because Google does not want any unauthorized repurposing. Which is understandable, a LOT of work went into it. But if you dig deep enough you'll get there for sure, and you can use the project page on hackaday to ask questions without info spilling public.

**Comment by jacobweber** [comment]
Looks like they've even removed the libsoda binaries and language pack files from Chrome 91. So better save your copy from Chrome 90. Not sure where they're stored now.

**Comment by ftamburin** [comment]
Could you please indicate me where to download Chrome v90 working on linux?
I have downloaded version 90.0.4430.72-1 but libsoda is not there. How can I get the extension?
Many thanks for your help.

**Comment by biemster** [comment]
You don't need specifically v90, just a newer version than 90. Any latest chrome or chromium will do.

**Comment by biemster** [comment]
@cppxaxa It should be in your chrome profile directory, but I don't have any windows machines to check this on so I can't really help you here.

**Comment by cppxaxa** [comment]
Thanks for the reply @biemster , confirming my resolution
I'm able to find out the "SODA.dll" and "SODALanguagePacks\en-US\1.0.2"

Although I moved a step forward, and I'm yet to try compiling and patching (currently facing issues though).
