### ISSUE TITLE
SODA.dll

### ISSUE THREAD

**Issue by ElijahHamilton** [biemster/gasr#7]
Hi! Is it possible you could email me the patched dll?
I do not have a good understanding of patching binaries.
Any response is appreciated!

elijah.w.hamilton@gmail.com

**Comment by biemster** [comment]
Fortunately it's not very difficult, and actually quite fun and educational:

1. Download Ghidra and analyze the DLL (there are plenty tutorials online for this, search for CTF cracking challenges)
2. Follow the entrypoint (the function that is called in the python / C client from this repo), until you get to three function calls that look like an API key check and a call stack verification (doing this first on the linux library helps a lot, since Ghidra can obtain the function names in this case)
3. use a technique like a NOP slide to bypass those checks
