### ISSUE TITLE
Failed to run make on ubuntu.

### ISSUE THREAD

**Issue by cleancoder7** [biemster/gasr#9]
Failed to make on Ubuntu 18.04

    /tmp/ccNlyHzy.o: In function `main':
    gasr.c:(.text+0x16d): undefined reference to `CreateSodaAsync'
    gasr.c:(.text+0x210): undefined reference to `AddAudio'
    gasr.c:(.text+0x234): undefined reference to `DeleteSodaAsync'
    collect2: error: ld returned 1 exit status

**Comment by laeuter** [comment]
What version of SODA are you using? They might have changed the API...

**Comment by biemster** [comment]
> What version of SODA are you using? They might have changed the API...

I'm not aware of an api change, @laeuter could you provide a commit in chromium for this? it still looks the same in master

**Comment by laeuter** [comment]
At least https://chromium.googlesource.com/chromium/src/+/refs/tags/95.0.4638.72/chrome/services/speech/soda/soda_client.cc uses function names with 'Extended' in their names, and the config is a protobuf. That looks different than the functions and configs gasr uses.

**Comment by goddade** [comment]
1.0.9 seems to have only "Extended" api.

**Comment by biemster** [comment]
It indeed seems Google dropped the easy API. The Extended functions need protobufs, but I won't build that in the C client as I only kept that around because I built that first, so I guess it's time to remove that now. The python client uses the Extended functions.

**Comment by alopez247** [comment]
I'm facing the same issue as cleancoder7, with the libsoda version 1.1.0.1. I understand the C version is no longer supported, but trying the python version, I still get errors:

I run the software like this: ecasound -f:16,1,16000 -i alsa -o:stdout | python3 gasr.py 

Below is the output. Any ideas on how to solve this?

********************************************************************************
*        ecasound v2.9.3 (C) 1997-2020 Kai Vehmanen and others
********************************************************************************
(eca-chainsetup) Chainsetup "untitled-chainsetup"
(eca-chainsetup) NOTE: Real-time configuration, but insufficient privileges to utilize real-time scheduling (SCHED_FIFO). With small buffersizes, this may cause audible glitches during processing.
(eca-chainsetup) "rt" buffering mode selected.
WARNING: Logging before InitGoogle() is written to STDERR
W0209 17:59:01.186751  400143 soda_async_impl.cc:323] Creating soda_impl.
W0209 17:59:01.186783  400143 soda_async_impl.cc:325] Created with thread priority 0
W0209 17:59:01.233304  400143 terse_processor.cc:859] Failed to fetch context module mdd download dir, cause: INVALID_ARGUMENT: Data provider is missing. Search process may not have been up.
=== Source Location Trace: ===
speech/audio/processor/terse_processor.cc:888
W0209 17:59:01.248485  400143 terse_processor.cc:336] TISID disabled.
W0209 17:59:01.254304  400165 portable_intended_query_stream.cc:235] Exiting due to stream cancellation.
W0209 17:59:01.254997  400143 decoder_endpointer_stream.cc:47] Acoustic ep reader thread cancelled.
W0209 17:59:01.255365  400143 soda_async_impl.cc:527] SODA session starting (require_hotword:0, hotword_timeout_in_millis:0, trigger_type:TRIGGER_TYPE_UNSPECIFIED, hybrid_asr_config.mode:MODE_DEFAULT)
(eca-chainsetup) Opened input "alsa", mode "read". Format: s16_le, channels 1, srate 16000, interleaved.
(audioio-raw) Outputting to standard output [rw].
(eca-chainsetup) Opened output "stdout", mode "read/write (update)". Format: s16_le, channels 1, srate 16000, interleaved.
[* Connected chainsetup: "untitled-chainsetup" *]
[* Controller/Starting batch processing *]
[* Engine - Driver start *]
W0209 17:59:01.776452  400146 soda_async_impl.cc:1287] SODA received first mic audio buffer, size in bytes: 640, format: 1, channels: 1, : sample rate: 16000
W0209 17:59:01.788287  400146 soda_async_impl.cc:1008] Not receiving any loopback audio in 500ms. Last audio received time: 0, Current time in us: 1644425941788287
W0209 17:59:03.341109  400190 portable_intended_query_stream.cc:235] Exiting due to stream cancellation.
W0209 17:59:03.342246  400146 decoder_endpointer_stream.cc:47] Acoustic ep reader thread cancelled.
W0209 17:59:04.166099  400206 portable_intended_query_stream.cc:235] Exiting due to stream cancellation.
W0209 17:59:04.166778  400146 decoder_endpointer_stream.cc:47] Acoustic ep reader thread cancelled.
W0209 17:59:04.993918  400221 portable_intended_query_stream.cc:235] Exiting due to stream cancellation.
W0209 17:59:04.994787  400146 decoder_endpointer_stream.cc:47] Acoustic ep reader thread cancelled.
W0209 17:59:05.818789  400235 portable_intended_query_stream.cc:235] Exiting due to stream cancellation.
W0209 17:59:05.819963  400146 decoder_endpointer_stream.cc:47] Acoustic ep reader thread cancelled.
W0209 17:59:06.737001  400251 portable_intended_query_stream.cc:235] Exiting due to stream cancellation.

**Comment by biemster** [comment]
I have neglected this project a bit lately, so I'm not sure. I do know that the proto needs updating, so that's one issue. @alopez247 
 You did patch the library right?
